spring.application.name=backend
spring.threads.virtual.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql = true

spring.web.error.include-message=always

# DEV ONLY ? replace with env var before production
jwt.secret=c2FuZHdoZWVsY2FyZHNpZ253aGVuZXZlcmRhbmNld2hlcmVyb3BlZGFuZ2Vyc3VtbWU=
#jwt.secret=${JWT_SECRET}
jwt.issuer=third-teen-api
jwt.expiration=3600
